# Generated by Django 4.1.3 on 2022-12-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('contacto_id', models.AutoField(primary_key=True, serialize=False)),
                ('contacto_nombres', models.CharField(max_length=20, verbose_name='Nombres Contacto')),
                ('contacto_correo', models.EmailField(max_length=40, verbose_name='Correo Contacto')),
                ('contacto_tema', models.CharField(max_length=100, verbose_name='Tema Contacto')),
                ('contacto_mensaje', models.CharField(max_length=255, verbose_name='Mensaje Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Eslogan',
            fields=[
                ('eslogan_id', models.AutoField(primary_key=True, serialize=False)),
                ('eslogan_proyecto', models.CharField(max_length=10, verbose_name='Eslogan Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Parrafoobjetivos',
            fields=[
                ('parrafoobjetivos_id', models.AutoField(primary_key=True, serialize=False)),
                ('parrafoobjetivos_contenido', models.CharField(max_length=255, verbose_name='Parrafo Objetivos')),
            ],
        ),
        migrations.CreateModel(
            name='Subobjetivo1',
            fields=[
                ('subobjetivo1_id', models.AutoField(primary_key=True, serialize=False)),
                ('subobjetivo1_contenido', models.CharField(max_length=255, verbose_name='Sub Objetivo 1')),
            ],
        ),
        migrations.CreateModel(
            name='Subobjetivo2',
            fields=[
                ('subobjetivo2_id', models.AutoField(primary_key=True, serialize=False)),
                ('subobjetivo2_contenido', models.CharField(max_length=255, verbose_name='Sub Objetivo 2')),
            ],
        ),
        migrations.CreateModel(
            name='Tec1',
            fields=[
                ('tec1_id', models.AutoField(primary_key=True, serialize=False)),
                ('tec1_contenido', models.CharField(max_length=255, verbose_name='Tecnologia 1')),
            ],
        ),
        migrations.CreateModel(
            name='Tec2',
            fields=[
                ('tec2_id', models.AutoField(primary_key=True, serialize=False)),
                ('tec2_contenido', models.CharField(max_length=255, verbose_name='Tecnologia 2')),
            ],
        ),
        migrations.CreateModel(
            name='Tec3',
            fields=[
                ('tec3_id', models.AutoField(primary_key=True, serialize=False)),
                ('tec3_contenido', models.CharField(max_length=255, verbose_name='Tecnologia 3')),
            ],
        ),
        migrations.CreateModel(
            name='Tec4',
            fields=[
                ('tec4_id', models.AutoField(primary_key=True, serialize=False)),
                ('tec4_contenido', models.CharField(max_length=255, verbose_name='Tecnologia 4')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('titulo_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_proyecto', models.CharField(max_length=10, verbose_name='Titulo Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(max_length=20, verbose_name='Nombre Usuario')),
                ('usuario_correo', models.EmailField(max_length=40, verbose_name='Correo Usuario')),
                ('usuario_clave', models.CharField(max_length=40, verbose_name='Clave Usuario')),
            ],
        ),
    ]
