# Generated by Django 4.1.3 on 2022-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eslogan',
            name='eslogan_proyecto',
            field=models.CharField(max_length=100, verbose_name='Eslogan Proyecto'),
        ),
    ]
